// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCTAyopHY7VTVaOiTA2kUHzzUgz9R3hf5Q',
//     appId: '1:359092619705:web:cf5461c7f5db36cb578e68',
//     messagingSenderId: '359092619705',
//     projectId: 'traveling-379316',
//     authDomain: 'traveling-379316.firebaseapp.com',
//     storageBucket: 'traveling-379316.appspot.com',
//     measurementId: 'G-6JDVNHG078',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAqNEdJddkv37bxUincZcgttx_WNkUQKdg',
//     appId: '1:359092619705:android:e6c063c9daa41890578e68',
//     messagingSenderId: '359092619705',
//     projectId: 'traveling-379316',
//     storageBucket: 'traveling-379316.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDN_zuyQ7tM4gJDquQ9JQGGrq0CO7hNqg4',
//     appId: '1:359092619705:ios:99116db95641437e578e68',
//     messagingSenderId: '359092619705',
//     projectId: 'traveling-379316',
//     storageBucket: 'traveling-379316.appspot.com',
//     iosClientId: '359092619705-681sqab72p4hr2917jfq47oc46itkpns.apps.googleusercontent.com',
//     iosBundleId: 'com.example.travelApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDN_zuyQ7tM4gJDquQ9JQGGrq0CO7hNqg4',
//     appId: '1:359092619705:ios:99116db95641437e578e68',
//     messagingSenderId: '359092619705',
//     projectId: 'traveling-379316',
//     storageBucket: 'traveling-379316.appspot.com',
//     iosClientId: '359092619705-681sqab72p4hr2917jfq47oc46itkpns.apps.googleusercontent.com',
//     iosBundleId: 'com.example.travelApp',
//   );
// }
